# this file is automatically generated
Gem::Specification.new do |s|
s.name = "findmyiphone"
s.version = "0.1.0"
s.summary = "MobileMe utilities"
s.description = "A toolkit for sending messages and getting location from MobileMe."
s.authors = ["Matt Biddulph"]
s.email = ["mb@hackdiary.com"]
 
s.files = ["examples/fireeagle_keys.yml.example", "examples/iphone_2_fireeagle.rb", "examples/iphone_credentials.yml.example", "lib/findmyiphone.rb", "Rakefile"]
s.require_paths = ["lib"]
 
s.add_dependency("mechanize", [">= 0.9.3"])
s.add_dependency("json", [">= 1.1.3"])
end
