require File.join("lib", "findmyiphone")
 
desc "Generate the gemspec"
task :gemspec do
  gemspec =<<-EOF
# this file is automatically generated
Gem::Specification.new do |s|
s.name = "findmyiphone"
s.version = "#{FindMyIphone::VERSION * "."}"
s.summary = "MobileMe utilities"
s.description = "A toolkit for sending messages and getting location from MobileMe."
s.authors = ["Matt Biddulph"]
s.email = ["mb@hackdiary.com"]
 
s.files = #{Dir.glob("**/*").select { |f| File.file?(f) }.inspect}
s.executables = ["findmyiphone"]
s.require_paths = ["lib"]
 
s.add_dependency("mechanize", [">= 0.9.3"])
s.add_dependency("json", [">= 1.1.3"])
end
EOF
 
  open("findmyiphone.gemspec", "w") do |f|
    f << gemspec
  end
 
  puts "gemspec successfully created."
end
 
task :default => :gemspec
